environment_prefix      = "prod"
location                = "UK South"
public_dns_zone_name    = "beta.bestinvest.co.uk"
dns_resource_group_name = "rg-uks-prod-digital-hybrid"
gtm_env_auth            = "qBaRWWRh__8d1pbtD357Iw"
gtm_env_preview         = "env-1"
