environment_prefix      = "staging"
location                = "UK South"
public_dns_zone_name    = "alpha.bi-digital.co.uk"
dns_resource_group_name = "rg-uks-staging-digital-hybrid"
gtm_env_auth            = "3CqRF6eWW4To0lvn8MquRA"
gtm_env_preview         = "env-7"
