name: Deploy to Azure Static Web

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hybrid-frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch_name

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Install dependencies
        run: |
          npm install -g gatsby-cli
          yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test

      - name: Build with Gatsby
        run: gatsby build

      - name: Run E2E UI tests
        run: |
          npx cypress install
          yarn test:e2e:ci

      - name: Setup storage account and enable static website hosting
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $StorageAccountRG = "digital-hybrid-resources"
            $StorageAccountName = "digitalhybridspike2"
            $IndexDocumentName = "index.html"
            $ErrorDocumentName = "error.html"
            if($(Get-AzStorageAccount -ResourceGroupName $StorageAccountRG -Name $StorageAccountName -ErrorAction Ignore) -eq $null) {
              Write-Host "Storage account doesnt exists, creating new storage account"
              New-AzureRmStorageAccount -Location "West Europe" -Name $StorageAccountName -ResourceGroupName $StorageAccountRG -SkuName Standard_GRS -Kind StorageV2
              Write-Host "New storage account created, enabling static website hosting"
              $storageAccount = Get-AzStorageAccount -ResourceGroupName $StorageAccountRG -AccountName $StorageAccountName
              $ctx = $storageAccount.Context
              Enable-AzStorageStaticWebsite -Context $ctx -IndexDocument $IndexDocumentName -ErrorDocument404Path $ErrorDocumentName
              Write-Host "Enabled static website hosting for ${{ steps.extract_branch_name.outputs.branch }}"
            } else {
              Write-Host "Storage account exists, deploy website"
            }
          azPSVersion: "latest"

      - name: Publish app
        uses: Azure/cli@v1.0.0
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch -s $GITHUB_WORKSPACE/hybrid-frontend/public -d "\$web" --account-name "digitalhybridspike2"